### ISSUE TITLE
Wo eigentlich LD_04

### ISSUE THREAD

**Issue by megamxl** [leonardo1710/MAD23LectureExamples#1]
![image](https://user-images.githubusercontent.com/78011818/225355513-8c14b81f-f2fe-403b-bced-c9b3ddd3f0f4.png)

**Comment by SpodoY** [comment]
![image](https://user-images.githubusercontent.com/72346498/225356043-d7ca713e-1a91-406d-9543-56d765a04cb4.png)

**Comment by megamxl** [comment]
![image](https://user-images.githubusercontent.com/78011818/225356249-7eebc240-d7be-4911-b734-83a2dac819c7.png)

**Comment by SpodoY** [comment]
![image](https://user-images.githubusercontent.com/72346498/225356593-c8409c52-6d42-49b3-85f4-f918474eca05.png)

**Comment by megamxl** [comment]
![image](https://user-images.githubusercontent.com/78011818/225357250-b2a712bc-ef32-456b-9f1e-36173608ab56.png)

**Comment by c2010475016** [comment]
![7el0qm](https://user-images.githubusercontent.com/71604752/225357618-be2fa11f-efa5-4d06-9732-31e5e112c102.jpg)

**Comment by SpodoY** [comment]
![image](https://user-images.githubusercontent.com/72346498/225357752-2c7de2d7-07e0-4efb-8d80-1a6dc32c06f0.png)
